[build]
# External packages that shouldn't be bundled
external = []

# Path mapping for build
[install]
# Registry configuration for Chinese users
registry = "https://registry.npmmirror.com"

[build.resolve]
# Enable path mapping
alias = "@" = "./src"